"""add cover_image to records

Revision ID: ec11126c6b0a
Revises: 88fab9e59901
Create Date: 2026-04-21 10:13:05.126612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec11126c6b0a'
down_revision: Union[str, Sequence[str], None] = '88fab9e59901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('cover_image', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'cover_image')
    # ### end Alembic commands ###
